(function(){"use strict";
let PERSONNEL=[];
const $=id=>document.getElementById(id),e={search:$("searchInput"),run:$("runSearch"),demo:$("loadDemo"),clear:$("clearSearch"),order:$("preserveOrder"),exact:$("exactPriority"),body:$("resultsBody"),empty:$("emptyState"),records:$("recordCount"),terms:$("termCount"),matches:$("matchCount"),elapsed:$("elapsed"),matched:$("matchedTerms"),unmatched:$("unmatchedTerms"),sort:$("sortDescription")};
const mode=()=>document.querySelector('input[name="mode"]:checked')?.value||"ANY";
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function pills(el,arr,warn){el.innerHTML=arr.length?arr.map(x=>`<span class="pill${warn?" warn":""}">${esc(x)}</span>`).join(""):"None"}
function mapCanonicalRecord(row,index){return{id:row["PERSONNEL SEARCH KEY"]||String(index+1),displayName:row["FULL NAME"]||row["CANONICAL NAME WITH RANK"]||row["CANONICAL NAME"]||"",canonicalName:row["CANONICAL NAME"]||"",personnelSearchKey:row["PERSONNEL SEARCH KEY"]||"",rank:row.RANK||"",office:row.Office||"",designation:row.Designation||"",camp:row.CAMP||"",lastName:row["LAST NAME"]||"",firstName:row["FIRST NAME"]||"",middleName:row["MIDDLE NAME"]||"",suffix:row.SUFFIX||"",canonicalNameWithRank:row["CANONICAL NAME WITH RANK"]||"",nameEngineVersion:row["NAME ENGINE VERSION"]||""}}
async function loadPersonnel(){e.empty.hidden=false;e.empty.textContent="Loading canonical personnel data…";const response=await fetch("./personnel-canonical-data.json",{cache:"no-store"});if(!response.ok)throw new Error(`Unable to load personnel-canonical-data.json (HTTP ${response.status})`);const rows=await response.json();if(!Array.isArray(rows))throw new Error("personnel-canonical-data.json must contain a JSON array.");PERSONNEL=rows.map(mapCanonicalRecord);e.records.textContent=PERSONNEL.length.toLocaleString();console.info(`Loaded ${PERSONNEL.length.toLocaleString()} canonical personnel records.`)}
function run(){if(!PERSONNEL.length){e.empty.hidden=false;e.empty.textContent="Canonical personnel data is not loaded yet.";return}const r=Level2Search.searchPersonnel(PERSONNEL,e.search.value,{mode:mode(),preserveInputOrder:e.order.checked,exactPriority:e.exact.checked});e.records.textContent=PERSONNEL.length.toLocaleString();e.terms.textContent=r.terms.length;e.matches.textContent=r.matches.length;e.elapsed.textContent=`${r.elapsedMs.toFixed(2)} ms`;pills(e.matched,r.matchedTerms,false);pills(e.unmatched,r.unmatchedTerms,true);e.sort.textContent=e.order.checked?"term order → quality → LIST order":"quality → LIST order";if(!r.matches.length){e.body.innerHTML="";e.empty.hidden=false;e.empty.textContent=r.terms.length?"No matches found.":"Enter search terms to begin.";return}e.empty.hidden=true;e.body.innerHTML=r.matches.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.term)}</td><td class="quality">${esc(x.qualityLabel)}</td><td>${esc(x.record.displayName)}</td><td>${esc(x.record.canonicalName)}</td><td>${esc(x.record.rank)}</td><td>${esc(x.record.office)}</td><td>${esc(x.record.camp)}</td></tr>`).join("");console.table(r.matches.map(x=>({term:x.term,quality:x.qualityLabel,name:x.record.canonicalName,sourceIndex:x.sourceIndex})))}
function showLoadError(error){console.error(error);e.empty.hidden=false;e.empty.textContent=`Failed to load personnel data: ${error.message}`;e.records.textContent="0";e.run.disabled=true;e.demo.disabled=true}
e.run.onclick=run;e.demo.onclick=()=>{e.search.value="Santos\nPostanes\nCruz\nUnknown Person";run()};e.clear.onclick=()=>{e.search.value="";run();e.search.focus()};e.search.addEventListener("keydown",x=>{if((x.ctrlKey||x.metaKey)&&x.key==="Enter")run()});document.querySelectorAll('input[name="mode"],#preserveOrder,#exactPriority').forEach(x=>x.addEventListener("change",run));
(async function init(){try{await loadPersonnel();run()}catch(error){showLoadError(error)}})();
})();
