(function(g){"use strict";
const Q={EXACT_KEY:0,EXACT_CANONICAL:1,STARTS:2,WHOLE_WORD:3,PARTIAL_CANONICAL:4,DISPLAY:5,OTHER:6};
const LABEL={0:"Exact search key",1:"Exact canonical",2:"Canonical starts with",3:"Whole-word canonical",4:"Partial canonical",5:"Display name",6:"Other field"};
function normalize(v){return String(v??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^\p{L}\p{N}\s'-]/gu," ").replace(/\s+/g," ").trim().toLowerCase()}
function parseTerms(raw){const seen=new Set();return String(raw??"").split(/[\n,;]+/).map(normalize).filter(t=>{if(!t||seen.has(t))return false;seen.add(t);return true})}
function wholeWord(text,term){const e=term.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return new RegExp(`(?:^|\\s)${e}(?:$|\\s)`,"i").test(text)}
function prep(r,i){const c=normalize(r.canonicalName),k=normalize(r.personnelSearchKey),d=normalize(r.displayName);return{record:r,sourceIndex:i,c,k,d,other:[r.rank,r.office,r.designation,r.camp].map(normalize)}}
function evaluate(n,t,exact){if(exact&&n.k===t)return{ok:true,q:Q.EXACT_KEY};if(exact&&n.c===t)return{ok:true,q:Q.EXACT_CANONICAL};if(n.c.startsWith(t))return{ok:true,q:Q.STARTS};if(wholeWord(n.c,t))return{ok:true,q:Q.WHOLE_WORD};if(n.c.includes(t))return{ok:true,q:Q.PARTIAL_CANONICAL};if(n.d.includes(t))return{ok:true,q:Q.DISPLAY};if(n.other.some(x=>x.includes(t)))return{ok:true,q:Q.OTHER};return{ok:false,q:Infinity}}
function searchPersonnel(records,raw,opt={}){const mode=opt.mode==="ALL"?"ALL":"ANY",preserve=opt.preserveInputOrder!==false,exact=opt.exactPriority!==false,terms=parseTerms(raw),start=performance.now();if(!terms.length)return{terms,matches:[],matchedTerms:[],unmatchedTerms:[],elapsedMs:performance.now()-start};const hitTerms=new Set(),matches=[];records.map(prep).forEach(n=>{const evals=terms.map((t,i)=>{const x=evaluate(n,t,exact);if(x.ok)hitTerms.add(i);return{term:t,termIndex:i,matched:x.ok,quality:x.q}});const accepted=mode==="ALL"?evals.every(x=>x.matched):evals.some(x=>x.matched);if(!accepted)return;const good=evals.filter(x=>x.matched);const best=good.reduce((a,b)=>!a||b.termIndex<a.termIndex||(b.termIndex===a.termIndex&&b.quality<a.quality)?b:a,null);matches.push({record:n.record,sourceIndex:n.sourceIndex,term:best.term,termIndex:best.termIndex,quality:best.quality,qualityLabel:LABEL[best.quality]})});matches.sort((a,b)=>(preserve?a.termIndex-b.termIndex:0)||a.quality-b.quality||a.sourceIndex-b.sourceIndex);return{terms,matches,matchedTerms:terms.filter((_,i)=>hitTerms.has(i)),unmatchedTerms:terms.filter((_,i)=>!hitTerms.has(i)),elapsedMs:performance.now()-start}}
g.Level2Search=Object.freeze({Q,LABEL,normalize,parseTerms,searchPersonnel});
})(window);
